### ISSUE TITLE
[enhanced-desktop-notifications] notification time

### ISSUE THREAD

**Issue by ildar** [acabal/thunderbird-addons#11]
the native TB notification has the setting of its time.
EDN time is too short and no (GUI) setting for it. I suggest two options:
1. just get TB notification time
2. have own setting

**Comment by acabal** [comment]
I don't understand what you're asking for, sorry!

**Comment by ildar** [comment]
![Снимок экрана от 2020-02-28 11-28-37](https://user-images.githubusercontent.com/517752/75513377-e5414480-5a1e-11ea-95a6-09b4c7a5a510.png)

**Comment by acabal** [comment]
OK, I see what you mean. If you're interested in working on a pull request that gets the TB setting and applies it to our notifications, I can merge that in. But, I don't have time to do this on my own at the moment, so I'll close this issue for now.
