### ISSUE TITLE
Hola Alex - Update request

### ISSUE THREAD

**Issue by xlovinglyx** [acabal/thunderbird-addons#15]
I'm looking for a chargeless contribution of one of leoncastro's addons, that used to hide 
every blue accounts including local folders [+ always puting outbox above trash]. 
Your addon only hides local folders & died at tb v73. I'll attach a fixed version of 
leon castro's abandoned addon if that can help you, but it stopped working 
at tb 72 or 73 i guess.

I told myself you had more experience in hiding folders since you created such addon.

**Comment by xlovinglyx** [comment]
http://s000.tinyupload.com/index.php?file_id=69623827314142373638

the xpi of leoncastro

**Comment by acabal** [comment]
Unfortunately I won't have time to work on this for the foreseeable future. If you can put together a working pull request then I'd be happy to review it.

**Comment by xlovinglyx** [comment]
I'm not a coder. Anyways, i get it, you abandon your addon too, i have to keep looking elsewhere. it's sad cause the functions don't demand a huge amount of code.

**Comment by GaVenga** [comment]
.....Unable....
WHO
