### ISSUE TITLE
TB  60.x compatible

### ISSUE THREAD

**Issue by Qrzysio** [acabal/thunderbird-addons#2]
Is there any possibility these extensions (ie. Mark Gmail Read) will be converted to the new format and become compatible with Thunderbird 60+?

**Comment by acabal** [comment]
Not in the short term. I'm still on Ubuntu 16.04 using TB 52.9.1, and I'm unfamiliar with the new TB plugin style. If you'd like to help, pull requests are welcomed.

**Comment by lorenzosu** [comment]
Hi Alex,
Looking forward to a possible update for TB 60+ for the enhanced desktop notifications addon which is great

**Comment by peci1** [comment]
Mark Gmail Read has been fixed (just wait a few days until it goes through the addon review process).

**Comment by acabal** [comment]
All extensions should be TB 60+ compatible now!

**Comment by Qrzysio** [comment]
Working well. Thank you!
