### ISSUE TITLE
Support for upcoming Thunderbird releases

### ISSUE THREAD

**Issue by tooomm** [acabal/thunderbird-addons#7]
Thunderbird is removing support for legacy add-ons (including MailExtensions with legacy support).

See https://developer.thunderbird.net/add-ons/tb78 with tips and some help on how to convert current add-ons to full MailExtensions or Web Extensions which are the new default to come for many years.

Is that possible at all?

<br>

More helpful? links:
- https://thunderbird-webextensions.readthedocs.io/en/latest/

**Comment by acabal** [comment]
Same answer as previously: if someone wants to help to make the migration then I'm more than happy to accept pull requests. But personally I won't be upgrading to TB 68+ for quite a while, so it's going to be up to someone else to work on that.

**Comment by tooomm** [comment]
Can you tell if it’s possible to upgrade the extensions at all and convert them to real mailextensions... as I don’t know the dependencies or requirements your extensions rely on.

**Comment by acabal** [comment]
I have no idea!

**Comment by RemcodM** [comment]
The hide local folders plugin seems to be working with Thunderbird 68 just fine, at least the version in the current master branch. What is the reason for not publishing the plugin on https://addons.thunderbird.net?

**Comment by tooomm** [comment]
@remcodm See #8, there has been some issues and nobody really knows what caused them.
